/** In-memory lattice profiles for demo mode — mirrors Firestore `lattice_profiles` */
export const mockLatticeProfiles = [
  {
    latticeId: 'captain_flystyle',
    userId: 1,
    name: 'Captain Flystyle',
    role: 'Lattice Mate',
    signal: 'Same bond, same weight, same voice as every other node on the lattice.',
    bio: 'Helm operator. Broadcasts across the moleculous when the deck needs direction.',
    color: '#c9a227',
    avatarUrl: null,
    isCoreCrew: true,
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    latticeId: 'b_mellow',
    userId: null,
    name: 'b mellow',
    role: 'Lattice Mate',
    signal: 'Holds the sub-pressure line open. Deep signal, steady bond.',
    bio: 'Low frequency anchor. Keeps the lattice grounded when the subs hit.',
    color: '#00ffcc',
    avatarUrl: null,
    isCoreCrew: true,
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    latticeId: 'bachon_blue',
    userId: null,
    name: 'বচোন blue',
    role: 'Lattice Mate',
    signal: 'Carries the blue-shift transmissions between decks and the void.',
    bio: 'Azure relay node on the equal lattice.',
    color: '#4da6ff',
    avatarUrl: null,
    isCoreCrew: true,
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    latticeId: 'phil_officer',
    userId: null,
    name: 'Phil Officer',
    role: 'Lattice Mate',
    signal: 'Keeps the watch rotation synced. First to ping when a mate boards.',
    bio: 'Watch officer — always on the lattice, never off duty.',
    color: '#ff00ff',
    avatarUrl: null,
    isCoreCrew: true,
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    latticeId: 'minton',
    userId: null,
    name: 'Minton',
    role: 'Lattice Mate',
    signal: 'Bridges the east-west moleculous arc. Quiet but always connected.',
    bio: 'Lattice bridge between crews east and west.',
    color: '#9d4edd',
    avatarUrl: null,
    isCoreCrew: true,
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    latticeId: 'tree',
    userId: null,
    name: 'tree',
    role: 'Lattice Mate',
    signal: 'Grounds the network. Old roots, deep memory, always listening.',
    bio: 'Root uplink. Deep memory on the lattice.',
    color: '#33ff99',
    avatarUrl: null,
    isCoreCrew: true,
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    latticeId: 'stu_ee',
    userId: null,
    name: 'stu-ee',
    role: 'Lattice Mate',
    signal: 'Repeats the crew heartbeat back through the chain. Never drops a signal.',
    bio: 'Echo pulse — the lattice heartbeat repeater.',
    color: '#ffe600',
    avatarUrl: null,
    isCoreCrew: true,
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
]
