export const demoUser = {
  id: 1,
  username: 'selector_k',
  email: 'k@tripship.com',
  displayName: 'Selector K',
  role: 'dj',
  createdAt: '1994-08-12T00:00:00.000Z',
}

export const mockMemories = [
  {
    id: 1,
    authorName: 'Maya Bass',
    title: 'Bristol Warehouse — New Year 96',
    content: 'Four K bins stacked to the ceiling. The whole floor was bouncing. Someone brought a strobelight on a washing line. When the amen dropped at 4am the roof felt like it was breathing. Pure Trip Ship energy.',
    eventYear: '1996',
    location: 'Easton, Bristol',
    createdAt: '2024-11-02T22:30:00.000Z',
  },
  {
    id: 2,
    authorName: 'Rude Boy Steve',
    title: 'Sound Clash at Carnival',
    content: 'Trip Ship rolled up with the full stack. Other sounds tried it but our bass weight was unmatched. Crowd went mad when we switched to jungle pressure. Still got the dubplate with my name on it.',
    eventYear: '1995',
    location: 'Notting Hill',
    createdAt: '2024-10-18T14:00:00.000Z',
  },
  {
    id: 3,
    authorName: 'Jungle Jane',
    title: 'First Time Hearing the Ship',
    content: 'I was 16. Mate dragged me to a free party in some disused factory. Didn\'t understand what I was hearing until the subs hit — proper chest compression. Been riding with Trip Ship ever since.',
    eventYear: '1993',
    location: 'Hackney Wick',
    createdAt: '2024-09-05T19:45:00.000Z',
  },
  {
    id: 4,
    authorName: 'Dubplate Dan',
    title: 'Sunrise Session on the Roof',
    content: 'Illegal rooftop set as the sun came up over the city. Mist rolling in, reggae into dub into jungle. Someone was cooking jerk chicken on a disposable BBQ. That\'s the Trip Ship I remember.',
    eventYear: '1997',
    location: 'Peckham',
    createdAt: '2024-08-21T06:15:00.000Z',
  },
]

export const mockMixes = [
  {
    id: 1,
    djName: 'Selector K',
    title: 'Jungle Pressure Vol. 7',
    description: 'Full power amen session. Roni Size, LTJ Bukem, Dillinja, and exclusive dubplates from the vault.',
    genre: 'Jungle / D&B',
    duration: '68 min',
    audioUrl: '#',
    createdAt: '2024-12-01T20:00:00.000Z',
  },
  {
    id: 2,
    djName: 'Dubplate Dan',
    title: 'Roots & Culture Trip',
    description: 'Deep dub and steppers for the sound system purists. Jah Shaka vibes through a 90s lens.',
    genre: 'Dub / Reggae',
    duration: '74 min',
    audioUrl: '#',
    createdAt: '2024-11-15T18:30:00.000Z',
  },
  {
    id: 3,
    djName: 'Garage Queen',
    title: '2-Step Midnight Selection',
    description: 'UK garage and speed garage from 98-99. Vocal cuts, swing beats, and bass that rolls.',
    genre: 'UK Garage',
    duration: '55 min',
    audioUrl: '#',
    createdAt: '2024-10-28T23:00:00.000Z',
  },
  {
    id: 4,
    djName: 'Hardcore Harry',
    title: 'Rave Accelerator 94',
    description: 'Hardcore and happy hardcore blast from the golden era. Piano stabs and breakbeats at 170.',
    genre: 'Hardcore',
    duration: '61 min',
    audioUrl: '#',
    createdAt: '2024-10-10T16:00:00.000Z',
  },
]
